from __future__ import annotations

import logging
import os
import re
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

ENV_PATTERN = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\}")

DEFAULTS: dict = {
    "database": {"path": "/data/errata.db"},
    "frigate": {
        "api_url": "http://frigate:5000",
        "username": "",
        "password": "",
        "request_timeout": 30,
        "snapshot_dir": "/data/snapshots",
        "config_path": "",
    },
    "harvest": {
        "interval_minutes": 30,
        "lookback_hours": 24,
        "min_confidence": 0.5,
        "max_confidence": 0.95,
        "max_events_per_run": 500,
        "max_pages": 20,
    },
    "analysis": {
        "vocabulary_coherence": True,
        "low_confidence_threshold": 0.75,
        "confirm_on_coherent_description": True,
        "auto_skip_implausible_boxes": True,
        "safe_labels": ["person", "car", "truck", "bicycle"],
        "synonyms": {
            "person": [
                "man", "woman", "child", "male", "female", "adult", "kid",
                "boy", "girl", "guy", "lady", "gentleman", "driver",
                "pedestrian", "courier", "worker", "delivery", "individual",
                "homeowner", "jogger", "shopper", "mailman", "mail carrier",
                "postman", "delivery driver",
            ],
            "car": [
                "sedan",
                "suv",
                "coupe",
                "hatchback",
                "minivan",
                "convertible",
                "wagon",
                "golf cart",
                "pickup",
                "vehicle",
                "ford",
                "honda",
                "toyota",
                "hyundai",
                "kia",
                "chevrolet",
                "chevy",
                "lexus",
                "mazda",
                "acura",
                "tesla",
                "nissan",
                "subaru",
                "volkswagen",
                "vw",
                "bmw",
                "mercedes",
                "mercedes-benz",
                "audi",
                "dodge",
                "jeep",
                "chrysler",
                "buick",
                "cadillac",
                "gmc",
                "volvo",
                "mini",
                "porsche",
                "mitsubishi",
                "infiniti",
                "genesis",
                "jaguar",
                "land rover",
                "rivian",
                "polestar",
                "fiat",
                "saturn",
                "pontiac",
                "mercury",
                "scion",
                "suzuki",
                "hummer",
                "lincoln",
                "alfa romeo",
                "maserati",
                "bentley",
                "ferrari",
                "lamborghini",
                "mclaren",
                "aston martin",
                "lotus",
                "oldsmobile",
                "plymouth",
                "isuzu",
                "daihatsu",
                "civic",
                "accord",
                "crv",
                "cr-v",
                "pilot",
                "odyssey",
                "hr-v",
                "hrv",
                "passport",
                "ridgeline",
                "insight",
                "prologue",
                "element",
                "camry",
                "corolla",
                "prius",
                "rav4",
                "highlander",
                "tacoma",
                "tundra",
                "4runner",
                "sienna",
                "avalon",
                "yaris",
                "venza",
                "sequoia",
                "land cruiser",
                "mustang",
                "escape",
                "focus",
                "fiesta",
                "fusion",
                "taurus",
                "explorer",
                "expedition",
                "edge",
                "flex",
                "bronco",
                "shelby",
                "maverick",
                "f-150",
                "f150",
                "f-250",
                "f250",
                "silverado",
                "malibu",
                "impala",
                "equinox",
                "tahoe",
                "suburban",
                "traverse",
                "camaro",
                "corvette",
                "colorado",
                "cruze",
                "sonic",
                "volt",
                "blazer",
                "trailblazer",
                "sonata",
                "elantra",
                "tucson",
                "santa fe",
                "accent",
                "veloster",
                "kona",
                "ioniq",
                "palisade",
                "venue",
                "optima",
                "forte",
                "rio",
                "soul",
                "sportage",
                "sorento",
                "telluride",
                "stinger",
                "k5",
                "carnival",
                "seltos",
                "niro",
                "altima",
                "sentra",
                "rogue",
                "pathfinder",
                "frontier",
                "maxima",
                "versa",
                "juke",
                "murano",
                "armada",
                "titan",
                "outback",
                "forester",
                "impreza",
                "crosstrek",
                "legacy",
                "ascent",
                "brz",
                "wrx",
                "golf",
                "jetta",
                "passat",
                "tiguan",
                "atlas",
                "beetle",
                "arteon",
                "gti",
                "model 3",
                "model y",
                "model s",
                "model x",
                "charger",
                "challenger",
                "durango",
                "journey",
                "caravan",
                "grand caravan",
                "avenger",
                "wrangler",
                "cherokee",
                "grand cherokee",
                "compass",
                "renegade",
                "gladiator",
                "liberty",
                "patriot",
                "sierra",
                "yukon",
                "canyon",
                "terrain",
                "acadia",
                "envoy",
                "escalade",
                "cts",
                "ats",
                "xts",
                "xt5",
                "xt4",
                "srx",
                "lacrosse",
                "encore",
                "enclave",
                "mazda3",
                "mazda6",
                "cx-5",
                "cx-9",
                "miata",
                "mx-5",
                "transit",
                "sprinter",
                "promaster",
            ],
            "cat": ["feline", "kitten", "kitty", "tabby", "calico", "tortoiseshell", "tomcat"],
            "dog": [
                "canine",
                "dog",
                "hound",
                "mutt",
                "pooch",
                "pup",
                "puppy",
                "retriever",
                "shepherd",
                "mixed breed",
                "rescue",
                "stray",
                "golden retriever",
                "labrador",
                "lab",
                "labrador retriever",
                "goldador",
                "chesapeake bay retriever",
                "flat coated retriever",
                "nova scotia duck tolling retriever",
                "cocker spaniel",
                "english cocker spaniel",
                "american cocker spaniel",
                "springer spaniel",
                "english springer spaniel",
                "welsh springer spaniel",
                "cavalier king charles spaniel",
                "english toy spaniel",
                "boykin spaniel",
                "brittany",
                "english setter",
                "irish setter",
                "gordon setter",
                "german shepherd",
                "belgian malinois",
                "malinois",
                "belgian sheepdog",
                "australian shepherd",
                "aussie",
                "australian cattle dog",
                "blue heeler",
                "border collie",
                "collie",
                "rough collie",
                "bearded collie",
                "old english sheepdog",
                "sheepdog",
                "shetland sheepdog",
                "sheltie",
                "cardigan welsh corgi",
                "pembroke welsh corgi",
                "welsh corgi",
                "corgi",
                "terrier",
                "bull terrier",
                "staffordshire bull terrier",
                "staffie",
                "american pit bull terrier",
                "american staffordshire terrier",
                "amstaff",
                "pit bull",
                "pitbull",
                "american bully",
                "jack russell",
                "jack russell terrier",
                "rat terrier",
                "fox terrier",
                "boston terrier",
                "cairn terrier",
                "norfolk terrier",
                "scottish terrier",
                "scottie",
                "west highland white terrier",
                "westie",
                "yorkshire terrier",
                "yorkie",
                "silky terrier",
                "rottweiler",
                "rottie",
                "doberman",
                "doberman pinscher",
                "boxer",
                "great dane",
                "mastiff",
                "bullmastiff",
                "cane corso",
                "great pyrenees",
                "bernese mountain dog",
                "saint bernard",
                "st bernard",
                "newfoundland",
                "akita",
                "alaskan malamute",
                "malamute",
                "siberian husky",
                "husky",
                "samoyed",
                "keeshond",
                "schipperke",
                "komondor",
                "kuvasz",
                "portuguese water dog",
                "rhodesian ridgeback",
                "ridgeback",
                "vizsla",
                "weimaraner",
                "giant schnauzer",
                "schnauzer",
                "norwegian elkhound",
                "beagle",
                "basset hound",
                "bloodhound",
                "coonhound",
                "bluetick coonhound",
                "redbone coonhound",
                "greyhound",
                "italian greyhound",
                "whippet",
                "saluki",
                "basenji",
                "dachshund",
                "wiener dog",
                "chihuahua",
                "pomeranian",
                "pug",
                "puggle",
                "maltese",
                "bichon frise",
                "bichon",
                "havanese",
                "shih tzu",
                "lhasa apso",
                "pekingese",
                "papillon",
                "japanese chin",
                "chinese crested",
                "brussels griffon",
                "miniature pinscher",
                "miniature schnauzer",
                "toy poodle",
                "miniature poodle",
                "standard poodle",
                "poodle",
                "bulldog",
                "english bulldog",
                "french bulldog",
                "frenchie",
                "american bulldog",
                "american eskimo",
                "dalmatian",
                "shar pei",
                "shiba inu",
                "shiba",
                "chow chow",
                "german shorthaired pointer",
                "german wirehaired pointer",
                "doodle",
                "goldendoodle",
                "labradoodle",
                "bernedoodle",
                "norwegian lundehund",
            ],
            "bird": [
                "crow", "raven", "owl", "sparrow", "hawk", "songbird", "robin",
                "pigeon", "dove", "finch", "cardinal", "quail", "blue jay",
                "duck", "goose", "chicken", "hen", "rooster", "chick",
                "eagle", "hummingbird", "woodpecker",
            ],
            "deer": ["buck", "doe", "fawn", "elk", "stag", "yearling", "moose"],
            "fox": ["vixen"],
            "rabbit": ["bunny", "hare", "cottontail"],
            "raccoon": [],
            "possum": ["opossum"],
            "skunk": [],
            "squirrel": [],
            "rodent": ["mouse", "mice", "rat", "chipmunk", "gopher", "vole"],
            "horse": [
                "pony", "foal", "mare", "stallion", "colt", "gelding",
                "donkey", "mule", "burro",
            ],
            "package": ["box", "parcel", "envelope", "cardboard", "mail", "shipment"],
            "garbage_truck": [
                "trash truck", "waste truck", "recycling truck",
                "garbage collection", "greenwaste", "refuse truck",
            ],
            "boat": [
                "vessel", "watercraft", "canoe", "kayak", "rowboat", "pontoon",
                "sailboat", "motorboat",
            ],
            "license_plate": ["plate", "plates", "number plate", "license tag"],
            "usps": [
                "mail truck", "postal truck", "postal van", "mail van",
                "postal service", "united states postal service",
            ],
            "ups": ["united parcel service", "ups truck", "ups van"],
            "fedex": [
                "federal express", "fedex truck", "fedex van", "fedex ground",
                "fedex express",
            ],
            "amazon": [
                "amazon truck", "amazon van", "amazon prime", "prime van",
                "amazon delivery",
            ],
            "dhl": ["dhl truck", "dhl van"],
            "gls": ["gls truck", "gls van"],
            "delivery_truck": [
                "delivery truck",
                "delivery van",
                "delivery vehicle",
                "delivery service",
                "box truck",
                "parcel truck",
                "package truck",
                "courier truck",
                "courier van",
                "freight truck",
                "step van",
                "cargo van",
                "route truck",
                "ups",
                "united parcel service",
                "fedex",
                "federal express",
                "fedex ground",
                "fedex express",
                "usps",
                "united states postal service",
                "postal truck",
                "postal van",
                "mail truck",
                "mail van",
                "dhl",
                "dhl express",
                "dhl ecommerce",
                "gls",
                "general logistics systems",
                "ontrac",
                "lasership",
                "lonestar",
                "veho",
                "axlehire",
                "pitney bowes",
                "newgistics",
                "osm worldwide",
                "speedx",
                "landmark global",
                "asendia",
                "purolator",
                "canada post",
                "royal mail",
                "dpd",
                "hermes",
                "evri",
                "yodel",
                "tnt",
                "aramex",
                "sf express",
                "jd logistics",
                "cainiao",
                "an post",
                "postnl",
                "bpost",
                "la poste",
                "chronopost",
                "colissimo",
                "mondial relay",
                "correos",
                "posti",
                "bring",
                "postnord",
                "amazon",
                "amazon prime",
                "amazon flex",
                "amazon logistics",
                "db schenker",
                "xpo logistics",
                "old dominion",
                "estes",
                "saia",
                "yrc",
                "abf freight",
                "tforce freight",
                "r+l carriers",
                "southeastern freight",
                "j.b. hunt",
                "jb hunt",
                "schneider",
                "swift",
                "werner",
                "ryder",
                "penske",
                "u-haul",
                "uhaul",
                "budget truck",
                "walmart",
                "target",
                "costco",
                "sam's club",
                "sams club",
                "home depot",
                "lowe's",
                "lowes",
                "best buy",
                "wayfair",
                "chewy",
                "hellofresh",
                "blue apron",
                "instacart",
                "doordash",
                "uber eats",
                "grubhub",
                "postmates",
                "shipt",
                "gopuff",
                "kroger",
                "safeway",
                "publix",
                "albertsons",
                "walgreens",
                "cvs",
                "rite aid",
                "pepsi",
                "pepsico",
                "coca-cola",
                "coca cola",
                "coke",
                "frito-lay",
                "frito lay",
                "sysco",
                "us foods",
                "gordon food service",
                "performance food group",
                "cintas",
                "unifirst",
                "aramark",
            ],
        },
        "suggestion_groups": {
            "animal": [
                "cat", "dog", "deer", "fox", "rabbit", "raccoon", "bird",
                "possum", "skunk", "squirrel", "rodent", "horse",
            ],
            "vehicle": ["car", "garbage_truck", "boat", "usps", "ups", "fedex", "amazon", "dhl", "gls", "delivery_truck"],
            "person": ["person"],
            "object": ["package", "license_plate"],
        },
        "noise": {"count": 10, "window_hours": 1},
    },
    "review": {"auto_keep_per_label": 150, "queue_limit": 200},
    "notifications": {"enabled": False, "discord_webhook": ""},
    "labels": {
        "track": [
            "car",
            "cat",
            "dog",
            "person",
            "license_plate",
            "usps",
            "ups",
            "fedex",
            "amazon",
            "dhl",
            "gls",
            "deer",
            "horse",
            "fox",
            "rabbit",
            "raccoon",
            "bird",
            "possum",
            "skunk",
            "squirrel",
            "rodent",
            "package",
            "garbage_truck",
            "boat",
            "delivery_truck",
        ]
    },
    "training": {
        "enabled": True,
        "trigger_threshold": 50,
        "dataset_dir": "/data/dataset",
        "model_output_dir": "/data/models",
        "publish_dir": "/publish",
        "keep_versions": 3,
        "model_type": "yolo11n",
        "epochs": 100,
        "imgsz": 640,
        "batch": 16,
        "amp": False,
        "workers": 4,
        "device": "cpu",
        "val_split": 0.1,
        "region_crops": True,
        "auto_update_frigate_config": False,
        "pseudo_labels": {
            "enabled": True,
            "per_camera_label_day": 3,
            "max_per_class": 250,
        },
    },
    "server": {"listen_host": "0.0.0.0", "listen_port": 8501, "base_path": "/errata"},
    "logging": {"level": "INFO"},
}


def expand_env(text: str) -> str:
    def repl(match: re.Match) -> str:
        name, default = match.group(1), match.group(2)
        return os.environ.get(name, default if default is not None else "")

    return ENV_PATTERN.sub(repl, text)


def deep_merge(base: dict, override: dict) -> dict:
    merged = dict(base)
    for key, value in (override or {}).items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def find_config_path(explicit: str | None = None) -> str | None:
    candidates = [
        explicit,
        os.environ.get("ERRATA_CONFIG"),
        "/config/errata.yaml",
        str(Path.cwd() / "config.yaml"),
    ]
    return next((c for c in candidates if c and Path(c).is_file()), None)


def load_config(explicit: str | None = None) -> dict:
    path = find_config_path(explicit)
    if path is None:
        logger.warning("no config file found, using built-in defaults")
        return deep_merge(DEFAULTS, {})
    text = expand_env(Path(path).read_text(encoding="utf-8"))
    data = yaml.safe_load(text) or {}
    config = deep_merge(DEFAULTS, data)
    logger.info("loaded config from %s", path)
    return config


def setup_logging(level: str = "INFO") -> None:
    logging.basicConfig(
        level=getattr(logging, str(level).upper(), logging.INFO),
        format="%(asctime)s %(levelname)-7s [%(name)s] %(message)s",
    )
